name: Create release branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'semver, e.g. v1.0.0'
        required: true

jobs:
  createRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}
      - name: Initialize mandatory git config
        run: |
         git config user.name "GitHub Actions"
         git config user.email noreply@github.com
      - name: Update Changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ github.event.inputs.version }}
      - name: Commit changelog
        id: make-commit
        run: |
          git add CHANGELOG.md
          git commit -m 'Prepare release ${{ github.event.inputs.version }}'
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.version }}
      - name: Create pull request to develop
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            head: release/${{ github.event.inputs.version }}
            base: develop
            title: ${{ github.event.inputs.version }} into develop
            reviewers: ${{ github.event.issue.user.login }}
            body: |
                Hi!
                This PR was created in response workflow running.
                I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
